import './guide.css';

const guide = document.createElement('section');
guide.id = 'guia';
guide.className = 'assembly-guide';
guide.setAttribute('aria-labelledby', 'guide-title');
guide.innerHTML = `
  <div class="guide-title-row"><div><p class="eyebrow">DEL MODELO A TU MESA</p><h2 id="guide-title">Dale vida de verdad<span>.</span></h2><p>Los componentes, cada cable y el código para armar tu propio Pequeñito.</p></div><a class="kit-button" href="./downloads/pequenito-kit.zip" download>Descargar kit completo <span>ZIP · código + instructivo</span></a></div>
  <div class="build-note"><strong>Una versión que podés construir.</strong> La carcasa y la cara toman como referencia el video. La electrónica de esta guía es una propuesta con XIAO ESP32C3: no se puede identificar con certeza la placa original. La demo es una visualización; el circuito requiere una prueba física antes de cerrar la carcasa.</div>
  <div class="guide-layout">
    <nav class="guide-nav" aria-label="Índice de armado"><a href="#componentes"><span>01</span>Qué comprar</a><a href="#pantalla"><span>02</span>La pantalla</a><a href="#conexiones"><span>03</span>Cada cable</a><a href="#programar"><span>04</span>Cargar el código</a><a href="#montaje"><span>05</span>Armar y probar</a><a href="#bateria"><span>06</span>Agregar batería</a><a href="#problemas"><span>07</span>Si algo falla</a><a href="#codigo"><span>08</span>Ver el código</a></nav>
    <div class="guide-content">
      <section id="componentes" class="guide-section"><p class="step-number">01 / MATERIALES</p><h3>Todo empieza con dos placas.</h3><p>Primero hacelo funcionar conectado por USB. Así podés comprobar la pantalla y las animaciones antes de soldar o agregar una batería.</p><div class="table-scroll"><table><thead><tr><th>Componente</th><th>Especificación</th><th>Cantidad</th></tr></thead><tbody>
        <tr><td>Microcontrolador</td><td><strong>Seeed Studio XIAO ESP32C3</strong>, con USB-C. Los pines de esta guía corresponden a ese modelo.</td><td>1</td></tr>
        <tr><td>Pantalla OLED</td><td><strong>0,96″ · 128×64 · SSD1306 · I²C</strong>, bicolor amarillo/azul, módulo de 4 pines compatible con alimentación y lógica de 3,3 V.</td><td>1</td></tr>
        <tr><td>Pulsador</td><td>Normalmente abierto, momentáneo. Usa la resistencia interna de la placa.</td><td>1</td></tr>
        <tr><td>Cable USB-C</td><td>De datos y alimentación. Un cable solo de carga no permite programar.</td><td>1</td></tr>
        <tr><td>Cables y protoboard</td><td>Jumpers para probar; cable fino flexible de 28–30 AWG para OLED/botón, y 26–28 AWG para batería.</td><td>1 juego</td></tr>
        <tr><td>Carcasa y herrajes</td><td>Acrílico aislante, separadores de nylon, tornillos, aro y mosquetón. Medí tus módulos antes de cortar.</td><td>1 juego</td></tr>
        <tr><td>Batería, opcional</td><td>LiPo <strong>1S, 3,7 V nominal / 4,2 V cargada</strong>, protegida y con corriente de carga admitida ≥500 mA. Ver sección 06.</td><td>1</td></tr>
        <tr><td>Interruptor, opcional</td><td>SPST para desconectar el positivo de batería, apto para al menos 1 A a 6 V CC.</td><td>1</td></tr>
      </tbody></table></div><p class="guide-small">Herramientas: computadora, multímetro, soldador de punta fina, estaño, termocontraíble o cinta aislante apropiada y herramientas para la carcasa.</p></section>
      <section id="pantalla" class="guide-section"><p class="step-number">02 / PANTALLA</p><h3>OLED, con dos zonas de color.</h3><div class="screen-spec"><div class="spec-number">128<span>×</span>64<small>PÍXELES</small></div><div><strong>SSD1306 · 0,96 pulgadas</strong><p>El modelo buscado tiene los 16 píxeles superiores amarillos y los 48 inferiores azules/celestes. El color pertenece a una zona física del panel: cuando un ojo se mueve, cambia de color al cruzarla.</p></div></div><p>Buscá: <strong>“OLED 0.96 SSD1306 128x64 I2C amarillo azul 4 pines”</strong>. Confirmá con el vendedor el controlador, la distribución del color y que el módulo funcione a 3,3 V. Un módulo SH1106, uno SPI de más pines o uno 128×32 necesita otra configuración.</p><p>El firmware dibuja píxeles encendidos y apagados. Una pantalla SSD1306 blanca también funciona, pero se verá de un solo color. La dirección I²C habitual es <code>0x3C</code>; algunos módulos usan <code>0x3D</code>.</p><p class="guide-small">La tecnología y el formato se eligieron por su parecido con el video; no hay un número de parte original confirmado.</p></section>
      <section id="conexiones" class="guide-section"><p class="step-number">03 / CONEXIONES</p><h3>Cuatro cables para la pantalla.</h3><p>Conectá todo con USB y batería desenchufados. Leé los nombres impresos en tu pantalla: <strong>el orden físico de los pines varía entre módulos.</strong></p>
        <div class="wiring-diagram"><svg viewBox="0 0 760 360" role="img" aria-labelledby="wiring-title wiring-desc"><title id="wiring-title">Conexión I²C entre XIAO ESP32C3, OLED y botón</title><desc id="wiring-desc">3V3 a VCC; GND a GND; D4 GPIO6 a SDA; D5 GPIO7 a SCL. Botón entre D2 GPIO4 y GND. Esquema lógico, no distribución física de los pines.</desc><rect x="35" y="26" width="235" height="230" rx="16" fill="#263a30" stroke="#577b61"/><text x="59" y="62" fill="#eaf5eb" font-size="19" font-weight="600">XIAO ESP32C3</text><text x="59" y="86" fill="#9eb5a5" font-size="13">MICROCONTROLADOR</text><rect x="505" y="26" width="220" height="230" rx="16" fill="#222b27" stroke="#577b61"/><text x="529" y="62" fill="#eaf5eb" font-size="19" font-weight="600">OLED SSD1306</text><text x="529" y="86" fill="#9eb5a5" font-size="13">128 × 64 · I²C</text>
        <g font-size="16" fill="#eaf5eb"><text x="60" y="124">3V3</text><text x="60" y="159">GND</text><text x="60" y="194">D4 / GPIO6</text><text x="60" y="229">D5 / GPIO7</text><text x="536" y="124">VCC</text><text x="536" y="159">GND</text><text x="536" y="194">SDA</text><text x="536" y="229">SCL</text></g><g fill="none" stroke-width="3"><path d="M253 119H522" stroke="#ec8b80"/><path d="M253 154H522" stroke="#b9c2b9"/><path d="M253 189H522" stroke="#75dfc6"/><path d="M253 224H522" stroke="#d4d774"/></g><g font-size="12" text-anchor="middle" fill="#9eb5a5"><text x="387" y="111">ALIMENTACIÓN · 3,3 V</text><text x="387" y="146">TIERRA COMÚN</text><text x="387" y="181">DATOS</text><text x="387" y="216">RELOJ</text></g><path d="M120 300H315m100 0h170" stroke="#75dfc6" fill="none" stroke-width="3"/><circle cx="317" cy="300" r="5" fill="#bcf8b6"/><circle cx="415" cy="300" r="5" fill="#bcf8b6"/><path d="M319 297l87-27" stroke="#bcf8b6" stroke-width="3"/><text x="35" y="305" font-size="15" fill="#eaf5eb">D2 / GPIO4</text><text x="602" y="305" font-size="15" fill="#eaf5eb">GND</text><text x="367" y="338" font-size="13" text-anchor="middle" fill="#9eb5a5">PULSADOR · NORMALMENTE ABIERTO</text></svg></div><p class="diagram-caption">Esquema lógico. Los bloques muestran qué unir; no representan la posición real de las patas.</p>
        <div class="table-scroll"><table><thead><tr><th>Desde la XIAO ESP32C3</th><th>Hasta</th><th>Función</th></tr></thead><tbody><tr><td><code>3V3</code></td><td>OLED <code>VCC</code></td><td>Alimentación de pantalla a 3,3 V.</td></tr><tr><td><code>GND</code></td><td>OLED <code>GND</code></td><td>Tierra común.</td></tr><tr><td><code>D4 / GPIO6</code></td><td>OLED <code>SDA</code></td><td>Datos I²C.</td></tr><tr><td><code>D5 / GPIO7</code></td><td>OLED <code>SCL</code></td><td>Reloj I²C.</td></tr><tr><td><code>D2 / GPIO4</code></td><td>Una terminal del pulsador</td><td>Entrada con <code>INPUT_PULLUP</code>.</td></tr><tr><td><code>GND</code></td><td>La otra terminal del pulsador</td><td>Al presionar, la entrada pasa a LOW.</td></tr></tbody></table></div><p>En pulsadores de cuatro patas, dos patas del mismo contacto suelen estar unidas internamente. Identificá con un multímetro los dos contactos que se cierran al presionar; no te guíes solo por la forma.</p><div class="guide-callout">Los GPIO del ESP32C3 trabajan a 3,3 V. En este montaje alimentá el OLED desde <code>3V3</code>. No conectes 5 V ni el positivo de batería a SDA, SCL o a un GPIO.</div></section>
      <section id="programar" class="guide-section"><p class="step-number">04 / FIRMWARE</p><h3>El código ya viene preparado.</h3><ol class="build-steps"><li><strong>Instalá Arduino IDE 2.</strong> Descargalo desde <a href="https://www.arduino.cc/en/software/" target="_blank" rel="noreferrer">Arduino</a>. En Preferencias agregá esta URL de placas adicionales: <code class="breakable">https://espressif.github.io/arduino-esp32/package_esp32_index.json</code>.</li><li><strong>Instalá la placa.</strong> En el gestor de placas instalá <code>esp32 by Espressif Systems 2.0.17</code>, la versión con la que se compiló este código. Seleccioná <code>XIAO_ESP32C3</code> y el puerto USB correspondiente.</li><li><strong>Instalá las bibliotecas.</strong> En el gestor de bibliotecas: <code>Adafruit SSD1306 2.5.17</code> y <code>Adafruit GFX Library 1.12.6</code>. Aceptá sus dependencias, incluida <code>Adafruit BusIO 1.17.4</code>.</li><li><strong>Abrí el sketch.</strong> Descomprimí el kit y abrí <code>firmware/pequenito/pequenito.ino</code>. Mantené el archivo dentro de la carpeta <code>pequenito</code>.</li><li><strong>Conectá el USB-C y cargá.</strong> Con la batería todavía desconectada, pulsá Verificar y luego Subir. El código configura SDA en GPIO6, SCL en GPIO7 y el botón en GPIO4.</li><li><strong>Probá las caras.</strong> Al iniciar se reproduce la secuencia automática. Un toque del botón pasa a la siguiente expresión y activa el modo manual; mantenerlo un segundo alterna entre modo manual y automático.</li></ol><div class="guide-callout"><strong>Si no permite subir:</strong> mantené presionado BOOT mientras conectás el USB, soltalo y volvé a seleccionar el puerto antes de subir. Usá el procedimiento de la documentación de Seeed para tu revisión de placa.</div><div class="guide-downloads"><a class="secondary-download" href="./downloads/pequenito.ino" download>Descargar código .ino</a><a class="secondary-download" href="./downloads/guia-de-armado.md" download>Descargar instructivo .md</a></div><p id="firmware-validation" class="guide-small">Compilación verificada para XIAO ESP32C3: 266.540 bytes de programa y 13.972 bytes de RAM global. El montaje todavía requiere una prueba con los componentes físicos.</p></section>
      <section id="montaje" class="guide-section"><p class="step-number">05 / ARMADO</p><h3>Probalo abierto. Cerralo al final.</h3><ol class="build-steps"><li><strong>Presentá las piezas.</strong> Ubicá OLED al frente, microcontrolador detrás y acceso al USB y al pulsador. Usá el modelo 3D para visualizar el aspecto; medí tus placas y batería para diseñar las separaciones reales.</li><li><strong>Hacé la prueba en protoboard.</strong> Conectá los cuatro cables y el pulsador según la tabla. Revisá VCC/GND y que no haya cortocircuito entre 3V3 y GND. Recién entonces conectá USB.</li><li><strong>Verificá las 16 expresiones.</strong> Comprobá el botón corto, la pulsación larga, el reinicio y la imagen. Si un problema aparece ahora, resolvelo antes de soldar.</li><li><strong>Pasá a cables cortos.</strong> Desconectá alimentación, soldá cada conexión y aislá las uniones. Evitá puentes entre pads y dejá alivio de tensión para que un tirón no arranque los cables.</li><li><strong>Separá las placas.</strong> Usá separadores y aislamiento; la cara trasera de la pantalla no debe tocar soldaduras de la XIAO. Reservá un hueco para el botón y el USB.</li><li><strong>Montá el acrílico.</strong> Fijá el aro a una parte resistente de la carcasa, nunca a los cables o al vidrio OLED. Ajustá los tornillos sin apretar la pantalla. Dejá la batería sin presión y lejos de puntas o rebabas.</li><li><strong>Hacé la prueba final.</strong> Ejecutá todas las caras varios minutos con el conjunto todavía accesible. Cerralo cuando la imagen, el botón, el encendido y la alimentación funcionen de manera estable.</li></ol><p class="guide-small">El GLB es un modelo visual con animaciones. Para cortar o imprimir una carcasa necesitás adaptar un plano CAD a las medidas exactas de tus componentes.</p></section>
      <section id="bateria" class="guide-section"><p class="step-number">06 / OPCIONAL</p><h3>Que pueda ir con vos.</h3><p>La XIAO ESP32C3 admite una batería de una celda en los pads <code>BAT+</code> y <code>BAT−</code> de su reverso, y tiene cargador integrado. Según Seeed, la carga rápida es de <strong>380 mA</strong>, con precarga de <strong>40 mA</strong>.</p><div class="power-path"><span>LiPo +</span><b>→</b><span>Interruptor</span><b>→</b><span>BAT+</span><span>LiPo −</span><b>→</b><span>BAT−</span></div><ol class="build-steps"><li><strong>Elegí por especificación.</strong> LiPo protegida 1S, 3,7 V nominal y 4,2 V de carga final. Su ficha debe admitir al menos 500 mA de carga. Una batería de 500 mAh solo sirve si su fabricante confirma esa corriente; la capacidad por sí sola no alcanza.</li><li><strong>Comprobá polaridad.</strong> Con USB desconectado, medí el pack con multímetro. Uní el positivo al interruptor y de allí a BAT+. Uní el negativo a BAT−. Usá un pack con cables o conector; no sueldes sobre la bolsa de la celda.</li><li><strong>Probá primero sin USB.</strong> Cerrá el interruptor: la placa debería iniciar. Abrilo: debería apagarse. Si no coincide, desconectá y revisá el circuito.</li><li><strong>Cargá por USB-C.</strong> Con el interruptor cerrado, el cargador puede llegar a la batería. Con el interruptor abierto, la batería queda aislada y no se carga. USB puede seguir alimentando el llavero aunque el interruptor esté apagado.</li></ol><div class="guide-callout"><strong>Antes de cerrar:</strong> aislá BAT+ y BAT− y evitá que el aro o los tornillos los toquen. No uses una celda hinchada, dañada o sin especificación de carga. Hacé las primeras cargas a la vista, sobre una superficie no combustible; desconectá si aparece calor anormal, olor o deformación.</div><p>La autonomía depende de la batería, la pantalla y el firmware. Este código no habilita Wi-Fi ni Bluetooth, pero no implementa suspensión profunda. Medí el consumo de tu montaje antes de estimar horas de uso. El circuito propuesto no incluye un indicador de porcentaje de batería.</p><p class="guide-small">Ejemplo de ficha para elegir: la <a href="https://www.adafruit.com/product/1578" target="_blank" rel="noreferrer">LiPo protegida de 500 mAh de Adafruit</a> especifica un máximo de carga de 500 mA. Revisá disponibilidad, dimensiones y ficha del producto concreto que compres.</p></section>
      <section id="problemas" class="guide-section"><p class="step-number">07 / DIAGNÓSTICO</p><h3>Si algo no sale a la primera.</h3><div class="troubleshooting"><details><summary>La pantalla queda negra</summary><p>Desconectá la alimentación y revisá VCC/GND, SDA→GPIO6 y SCL→GPIO7. Confirmá que sea SSD1306 de 128×64 I²C. El firmware informa el inicio por Serial a 115200 baudios; si no encuentra el OLED, consultá el diagnóstico del sketch y la dirección del módulo. Evitá cambiar cables con alimentación conectada.</p></details><details><summary>El OLED usa otra dirección</summary><p>El código detecta automáticamente <code>0x3C</code> y <code>0x3D</code>, y reintenta cada dos segundos si no hay respuesta. Consultá Serial a 115200 baudios. Si ninguna responde, confirmá cableado y tensión; también podés usar un escáner I²C. La detección de dirección no identifica el controlador de pantalla.</p></details><details><summary>El botón no cambia de cara</summary><p>Debe cerrar GPIO4 a GND, no a 3V3. En pulsadores de cuatro patas verificá con continuidad los dos contactos. El código ya usa resistencia interna y antirrebote.</p></details><details><summary>No aparece el puerto o no sube el programa</summary><p>Probá un cable USB de datos, revisá el puerto y la placa XIAO_ESP32C3. Si hace falta, conectá USB manteniendo BOOT y luego soltalo para entrar en modo de descarga.</p></details><details><summary>Los colores no son iguales</summary><p>El firmware no puede convertir una pantalla blanca en bicolor. El panel debe tener su franja amarilla física. La intensidad y el tono varían entre módulos y con la exposición de una cámara.</p></details><details><summary>Se reinicia al desconectar USB</summary><p>Revisá batería cargada, polaridad, BAT+/BAT− e interruptor. El OLED debe seguir tomando alimentación de 3V3. No conectes la LiPo directamente a 3V3; una celda llena alcanza 4,2 V.</p></details></div></section>
      <section id="codigo" class="guide-section"><p class="step-number">08 / CÓDIGO ABIERTO PARA VOS</p><h3>Las caras están en el código.</h3><p>El mismo kit incluye las 16 expresiones de la demo, temporización sin bloqueos, antirrebote del botón y reproducción automática. Podés editar los dibujos y tiempos en Arduino IDE.</p><details class="code-details"><summary>Ver firmware completo <span>Arduino / C++</span></summary><div class="code-toolbar"><span>pequenito.ino</span><button id="copy-firmware">Copiar código</button></div><pre><code id="firmware-source">Abrí esta sección para cargar el código.</code></pre></details><div class="guide-sources"><h4>Documentación para consultar</h4><a href="https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/" target="_blank" rel="noreferrer">Seeed · XIAO ESP32C3: pines, alimentación y programación</a><a href="https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html" target="_blank" rel="noreferrer">Espressif · instalación de ESP32 en Arduino IDE</a><a href="https://www.lcdwiki.com/0.96inch_OLED_Module_%28IIC-4P_SKU%3AMC096VX%29" target="_blank" rel="noreferrer">QD / LCDWiki · módulo OLED MC096VY, SSD1306 amarillo/azul</a><a href="https://github.com/adafruit/Adafruit_SSD1306" target="_blank" rel="noreferrer">Adafruit · biblioteca SSD1306</a><a href="https://learn.adafruit.com/monochrome-oled-breakouts/arduino-library-and-examples" target="_blank" rel="noreferrer">Adafruit · pantalla OLED, biblioteca y ejemplos</a></div></section>
    </div>
  </div>`;
document.querySelector('main footer').before(guide);

let firmwareText = '';
const codeDetails = guide.querySelector('.code-details');
codeDetails.addEventListener('toggle', async () => {
  if (!codeDetails.open || firmwareText) return;
  const code = guide.querySelector('#firmware-source');
  code.textContent = 'Cargando código…';
  try {
    const response = await fetch(new URL('./downloads/pequenito.ino', document.baseURI));
    if (!response.ok) throw new Error('No disponible');
    firmwareText = await response.text();
    if (!firmwareText.includes('#include')) throw new Error('Archivo incorrecto');
    code.textContent = firmwareText;
  } catch { firmwareText = ''; code.textContent = 'No se pudo cargar el código. Podés descargar el kit completo e intentar de nuevo.'; }
});
guide.querySelector('#copy-firmware').addEventListener('click', async event => {
  const button = event.currentTarget;
  if (!firmwareText) return;
  try { await navigator.clipboard.writeText(firmwareText); button.textContent = 'Copiado'; }
  catch { button.textContent = 'Seleccioná y copiá el texto'; }
  setTimeout(() => { button.textContent = 'Copiar código'; }, 2500);
});
